version: "3"
 
services:
  jenkins:
    user: root
    image: jenkins:2.60.3
    ports:
      - "8080:8080"
    volumes:
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
